### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by kpimarianenko** [kpimarianenko/homepage#10]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by zayzevnetov** [comment]
**I am the legendary chieftain of the Warsong clan, a powerful warrior, close friend, and greatest lieutenant to Warchief Thrall. He was the first orc who drank the blood of Mannoroth the Destructor, thus binding the Horde to the Burning Legion — and he would eventually pay the ultimate price to free himself and his people from the Blood Curse.**
