### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by kpimarianenko** [kpimarianenko/homepage#5]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by zayzevnetov** [comment]
Satou Kazuma (佐藤さとう 和真かずま) is the main protagonist of the KonoSuba series. He was reincarnated into the Fantasy World after dying. Kazuma is a young man of average height and weight. He has short and slightly spiky chestnut-brown hair and green eyes. His usual outfit consists of a gold-trimmed green mantle, white shirt, pants, and leather boots. He initially wore a green tracksuit. He usually wears his shortened katana, Chunchunmaru, on his belt.
