### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by kpimarianenko** [kpimarianenko/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by zayzevnetov** [comment]
https://konosuba.fandom.com/wiki/Satou_Kazuma
http://seasonvar.ru/serial-13006-Boginya_blagoslovlyaet_etot_prekrasnyj_mir-1-season.html
senpaigram.me/kazuma
kawaiibook.com/kazuma
