### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by kpimarianenko** [kpimarianenko/homepage#7]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by zayzevnetov** [comment]
Kazuma died many times:
1. In Japan, from shock.
2. In the second volume of KonoSuba at the hands of Jack Frost. Beheaded.
3. In the fourth volume of KonoSuba from falling from a tree, after the assassination of the Queen of Runners. The neck is broken.
4. In the sixth volume of KonoSuba, when he was surrounded by many kobolds. Dead to death.
5. In the seventh volume of KonoSuba, when he was swallowed by the Kowloon Hydra. It is dissolved in digestive juices.
6. In the fifteenth volume of KonoSuba at the hands of Celestine. Instant death spell.
7. In the fourth volume, Bakuen is from a monster that looks like an ant lion. Cut into two halves.
8. In the first OVA episode after putting on a damned necklace. Strangled to death. (this death was not in the novel)
9. In the anime series 20, when he became the bait for Hans. Dissolved to the state of the skeleton. (this death was not in the novel)
10. In a feature film when merged with Sylvia. Amazed at the combined spell of explosion magic and advanced magic. (this death was not in the novel)
