### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by kpimarianenko** [kpimarianenko/homepage#9]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by zayzevnetov** [comment]
**Discord: GromHellscream#3941
Blizzard: GrommashWOW#4258
Instagram: https://www.instagram.com/grom_the_warrior/
Twitter: https://twitter.com/warlordgrom**
